.TH JOYN 1 2024-02-12 1.0.0 ""
.SH NAME
\fBjoyn\fR \- Join lines
.SH SYNOPSIS
\fBjoyn\fR [\fB-d\fR \fI<delimiter>\fR] [\fI<file> \.\.\.\fR]
.SH DESCRIPTION
Joins lines, optionally using the specified delimeter.
.SH OPTIONS
.TP
\fB\-d, \-\-delimeter\fR
The line delimeter\.
.TP
\fB\-h, \-\-help\fR
Print help\.
.TP
\fB\-v\, \-\-version\fR
Print the version\.
.SH INSTALLATION
Install:
.PP
.RS 4
brew install nicholasdower/tap/joyn
.RE
.PP
Uninstall:
.PP
.RS 4
brew uninstall joyn
.RE
